## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 11;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

%global forgename gitlab
%global forgeurl https://www.opencode.net/trialuser/qt6ct
%global commit 00823e41aa60e8fe266d5aee328e82ad1ad94348
%global shortcommit %(c=%{commit}; echo ${c:0:7})
%forgemeta

Name:    qt6ct
Version: 0.11
Release: %autorelease
Summary: Qt6 - Configuration Tool

License: BSD-2-Clause
URL:     %{forgeurl}

Source0: %{forgesource}
# https://www.opencode.net/trialuser/qt6ct/-/merge_requests/9
#Patch0:  qt6ct-kde.patch
Patch1:  0001-build-refactor-CMake-build-rules.patch
#Patch2:  0002-Wrap-forward-declaration-within-QT_NAMESPACE.patch
#Patch3:  0003-Revert-Use-KDE-s-QtQuick-QtWidgets-style-bridge.patch

#Patch4:  qt6ct-fix-build-against-qt-6-10.patch

BuildRequires: cmake
BuildRequires: extra-cmake-modules

BuildRequires: desktop-file-utils
BuildRequires: gcc-c++
BuildRequires: cmake(Qt6Core)
BuildRequires: cmake(Qt6Widgets)
BuildRequires: cmake(Qt6QuickControls2)
BuildRequires: cmake(Qt6LinguistTools)
BuildRequires: qt6-qtbase-private-devel
BuildRequires: cmake(KF6Config)
BuildRequires: cmake(KF6ColorScheme)
BuildRequires: cmake(KF6IconThemes)

%{?_qt6:Requires: %{_qt6}%{?_isa} = %{_qt6_version}}

%description
This program allows users to configure Qt6 settings (theme, font, icons, etc.)
under DE/WM without Qt integration.

%prep
%forgeautosetup -p1
#autosetup -p1


%build
%cmake -DQT6CT_IN_TREE=ON
%cmake_build

%install
%cmake_install
%find_lang %{name} --with-qt

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/*.desktop

%files -f %{name}.lang
%doc AUTHORS README.md ChangeLog
%license COPYING
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%dir %{_datadir}/%{name}/
%dir %{_datadir}/%{name}/colors/
%{_datadir}/%{name}/colors/*.conf
%dir %{_datadir}/%{name}/qss/
%{_datadir}/%{name}/qss/*.qss
%exclude %{_libdir}/libqt6ct-common.so
%{_libdir}/libqt6ct-common.so.%{version}
%{_qt6_plugindir}/platformthemes/libqt6ct.so
%{_qt6_plugindir}/styles/libqt6ct-style.so

%changelog
## START: Generated by rpmautospec
* Fri Nov 21 2025 Jan Grulich <jgrulich@redhat.com> - 0.11-10
- Rebuild (qt6)

* Wed Oct 08 2025 Jan Grulich <jgrulich@redhat.com> - 0.11-9
- Rebuild (qt6)

* Wed Oct 01 2025 Jan Grulich <jgrulich@redhat.com> - 0.11-8
- Fix build against Qt 6.10

* Tue Sep 30 2025 Jan Grulich <jgrulich@redhat.com> - 0.11-7
- Rebuild (qt6)

* Mon Sep 08 2025 Zephyr Lykos <git@mochaa.ws> - 0.11-6
- Don't use KDE's QtQuick-QtWidgets style bridge

* Mon Sep 08 2025 Zephyr Lykos <git@mochaa.ws> - 0.11-5
- Use find_lang macros

* Mon Sep 08 2025 Zephyr Lykos <git@mochaa.ws> - 0.11-4
- Wrap forward declaration within QT_NAMESPACE

* Mon Sep 08 2025 Zephyr Lykos <git@mochaa.ws> - 0.11-3
- Refactor CMake build rules

* Sun Sep 07 2025 Zephyr Lykos <fedora@mochaa.ws> - 0.11-1
- New version, switch upstream URL
- Use CMake to build, remove unused BR
- Add KDE theming support
- Remove ExcludeArch s390x

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.9-14
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Tue Mar 25 2025 Jan Grulich <jgrulich@redhat.com> - 0.9-13
- Rebuild (qt6)

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.9-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Mon Oct 14 2024 Jan Grulich <jgrulich@redhat.com> - 0.9-11
- Rebuild (qt6)

* Wed Sep 04 2024 Miroslav Suchý <msuchy@redhat.com> - 0.9-10
- convert license to SPDX

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.9-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Thu Apr 04 2024 Jan Grulich <jgrulich@redhat.com> - 0.9-8
- Rebuild (qt6)

* Fri Feb 16 2024 Jan Grulich <jgrulich@redhat.com> - 0.9-7
- Rebuild (qt6)

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.9-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Mon Jan 22 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.9-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Wed Nov 29 2023 Jan Grulich <jgrulich@redhat.com> - 0.9-4
- Rebuild (qt6)

* Fri Oct 13 2023 Jan Grulich <jgrulich@redhat.com> - 0.9-3
- Rebuild (qt6)

* Thu Oct 05 2023 Jan Grulich <jgrulich@redhat.com> - 0.9-2
- Rebuild (qt6)

* Wed Sep 27 2023 Martin Gansser <martinkg@fedoraproject.org> - 0.9-1
- Update to 0.9-1

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.8-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Wed Jul 12 2023 Jan Grulich <jgrulich@redhat.com> - 0.8-5
- Rebuild for qtbase private API version change

* Wed Jul 12 2023 Jan Grulich <jgrulich@redhat.com> - 0.8-4
- Rebuild for qtbase private API version change

* Mon May 29 2023 Jan Grulich <jgrulich@redhat.com> - 0.8-3
- Rebuild (qt6)

* Thu May 18 2023 Martin Gansser <martinkg@fedoraproject.org> - 0.8-2
- Rebuilt against new qt6 version

* Mon Mar 13 2023 Martin Gansser <martinkg@fedoraproject.org> - 0.8-1
- Update to 0.8-1

* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Mon Nov 21 2022 Martin Gansser <martinkg@fedoraproject.org> - 0.7-1
- Update to 0.7-1

* Sat Oct 22 2022 Martin Gansser <martinkg@fedoraproject.org> - 0.7-0.1.git4e881ab
- Fix crash with a segmentation fault when closing the tool

* Wed Sep 21 2022 Martin Gansser <martinkg@fedoraproject.org> - 0.6-0.1.git6abd586
- New Snapshot version

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.5-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Wed Oct 06 2021 Martin Gansser <martinkg@fedoraproject.org> - 0.5-1
- Update to 0.5
- Add ExcludeArch s390x

* Sat Aug 28 2021 Martin Gansser <martinkg@fedoraproject.org> - 0.4-2
- Add missing desktop file validation
- Add BR desktop-file-utils

* Wed Aug 11 2021 Martin Gansser <martinkg@fedoraproject.org> - 0.4-1
- Update to 0.4
- Fix unowned directories

* Thu Jul 01 2021 Martin Gansser <martinkg@fedoraproject.org> - 0.3-1
- Update to 0.3

* Mon Feb 08 2021 Martin Gansser <martinkg@fedoraproject.org> - 0.2-1
- initial Build

## END: Generated by rpmautospec
